#!/system/bin/sh
# Sets up various parameters for MiniCM
# Author: nobodyAtall @ xda

if [ -e /system/bin/log ];
then
    LOGI="log -p i -t mountsd --"
    LOGE="log -p e -t mountsd --"
else
    LOGI=echo
    LOGE=echo
fi

DEFAULT_KB="128KB"
DEFAULT=`/system/xbin/echo $DEFAULT_KB | /system/xbin/sed 's/KB//'`
PROP_KB=`getprop persist.sys.sdcardcachereadsize`
PROP=`/system/xbin/echo $PROP_KB | /system/xbin/sed 's/KB//'`

if [ -f /sbin/recovery ]; then
	RECVERSION=`strings /sbin/recovery|/system/xbin/grep Recovery | /system/xbin/head -n 1`
	setprop ro.recversion "$RECVERSION"
elif [ -f /system/bin/recovery.tar ]; then
	RECVERSION=`/system/xbin/strings /system/bin/recovery.tar | /system/xbin/grep ClockworkMod|/system/xbin/head -n 1`
	setprop ro.recversion "$RECVERSION"
elif [ -f /system/bin/xrecovery.tar ]; then
	RECVERSION=`/system/xbin/strings /system/bin/xrecovery.tar | /system/xbin/grep xRecovery`
	setprop ro.recversion "$RECVERSION"
fi

if [ -n "$PROP_KB" ];
then
	$LOGI "defined sdcard cache read size is $PROP_KB"
	if [ -e /sys/devices/virtual/bdi/179:0/read_ahead_kb ]
	then
		/system/xbin/echo $PROP > /sys/devices/virtual/bdi/179\:0/read_ahead_kb
	fi
else
	$LOGI "no sdcard cache read size defined, using default of $DEFAULT_KB"
	setprop persist.sys.sdcardcachereadsize $DEFAULT_KB
	/system/xbin/echo $DEFAULT > /sys/devices/virtual/bdi/179:0/read_ahead_kb
fi

KERNELVERSION=`cat /proc/version |awk {'print $3'}`
setprop ro.kernelversion "$KERNELVERSION"

